language: node_js
sudo: false
node_js:
  - node
env:
  - NODE_ENV=production
before_install:
  - npm install -g npm
  - npm install -g eslint
install:
  - npm install
script:
  - npm run build
  - npm run lint
  - npm test
after_success: npm run build:codecov
