language: node_js
sudo: false
node_js:
  - node
matrix:
  include:
    - node_js: 4.0
      env: NODE_ENV=production
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm test
after_success: npm run build:codecov
