language: node_js
sudo: false
node_js:
  - node
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm run build
  - npm run lint
  - npm test
after_success: npm run build:codecov
